### ISSUE TITLE
Feature request: atLeast and atMost methods

### ISSUE THREAD

**Issue by philwolstenholme** [nicolas-cusan/breakpoint-helper#1]
It'd be really useful to be able to do something like `atLeast('lg')` or `atMost('md')`.

This is an idea I took from the [Foundation media query JS utility](https://get.foundation/sites/docs/media-queries.html#js-functions) supports this, and [BreakJS](https://github.com/nygardk/BreakJS#usage) too.

We can do this already by passing a min and max range to `isMatching`, e.g. `atLeast('lg')` could be expressed as `isMatching('lg', 'xxl')` but then if I ever added a `xxxl` breakpoint I would have to go back and edit all the instances of `isMatching('lg', 'xxl')` to be `isMatching('lg', 'xxxl')` instead.

**Comment by nicolas-cusan** [comment]
Hello @philwolstenholme,

thank you for filing this issue. You can already do something like `atLeast` and `atMost` using `isMatching`:

```js
if (isMatching('md')) {
  // Do something if screen is larger than `md`
}

if (isMatching('md', true)) {
  // Do something if screen is smaller than `md`
}

if (isMatching(['md', 'lg'])) {
  // To match between two breakpoints you need to pass an array (not two arguments as in your example)
}
```
Also see here: https://nicolas-cusan.github.io/breakpoint-helper/#ismatchingname-usemaxfalse

**Comment by philwolstenholme** [comment]
Oh nice! I forgot it was all based on just `min-width` or `max-width` and was assuming that `(isMatching('md'))` would return `FALSE` if the screen was `lg`, but I can see why I was wrong now.
