### ISSUE TITLE
React hook example

### ISSUE THREAD

**Issue by merobal** [nicolas-cusan/breakpoint-helper#4]
Thanks for this lib!

Just for the record, we use this small react hook, maybe useful for others as well.

_(We use TypeScript, so we had to cast the tailwind config and this lib as `any`. If you have time please consider adding types support to the roadmap.)_

```
import { useCallback, useEffect, useState } from "react";

const breakpointHelper: any = require("breakpoint-helper").default;
const tailwindConfig: any = require("../../../tailwind.config.js");

const instance = breakpointHelper(tailwindConfig.theme.screens);

const { listenAll } = instance;

export const useBreakpoint = () => {
  const [match, setMatch] = useState<string>();

  const callback = useCallback((bps: string[]) => {
    setMatch(bps[0]);
  }, []);

  useEffect(() => {
    const listener = listenAll(callback, { immediate: true });

    return () => listener.off();
  }, [callback]);

  return match;
};
```

**Comment by merobal** [comment]
Thanks for the suggestions!

We don't use SSR, it's a Laravel Mix project, so only client-side React.

Also in the Tailwind docs:

>Note that this will transitively pull in a lot of our build-time dependencies, resulting in bigger bundle client-side size. To avoid this, we recommend using a tool like babel-plugin-preval to generate a static version of your configuration at build-time

I tried to setup `babel-plugin-preval` but I had no success in the `Laravel Mix & TypeScript & React` world. Then I realized we only use our custom colors and breakpoints defined in our config file, so it's enough to import that, which results smaller bundle size.

**Comment by nicolas-cusan** [comment]
Hi @merobal 

Long time... I have rewritten the lib in Typescript. If you have a chance to check it out it would be great to know if it works well for you, it is my first time a publishing something on npm using Typescript.

I also added an simple example on usage with react. Will close this issue now. I you have any problems feel free to open a new issue.

**Comment by merobal** [comment]
I tested it now, and got this error message:
`import breakpointHelper from "breakpoint-helper";` =>
`File /node_modules/breakpoint-helper/dist/breakpoint-helper.d.ts' is not a module.ts(2306)`

**Comment by nicolas-cusan** [comment]
Hey @merobal, thank you for your feedback, I released a fix. Please let me know if it works for you.

**Comment by merobal** [comment]
It works now!
