### ISSUE TITLE
[Bug] On Safari 13 (ios 13) and earlier

### ISSUE THREAD

**Issue by merobal** [nicolas-cusan/breakpoint-helper#7]
We found a bug which occurs on old safari (unfortunately few of our users use old version and don't want to upgrade...)

Tested via https://www.lambdatest.com/ 

The error in production: `TypeError: n.addEventListener is not a function. (In 'n.addEventListener("change",t)', 'n.addEventListener' is undefined)`

And the code context indicated that the source of the issue is this line:
https://github.com/nicolas-cusan/breakpoint-helper/blob/master/src/index.js#L192 (`mq` can be undefined.)

I put our `listener = listenAll(callback);` line inside a try-catch and our prod issue disappeared.

Can you please fix this issue (add an undefined check for `mq` would be enough for us) and release?

**Comment by nicolas-cusan** [comment]
Hey @merobal, thank you for filing this issue.

I am pretty busy at the moment, but if you file a PR I will consider merging it.

Just out of curiosity: what code are you using to invoke the instance? What version iOS version has this error as `window.matchMedia` is supported since iOS/safari 5.

**Comment by merobal** [comment]
We use the code I showed at #4

Not sure why the bug occurred, I was able to reproduce at online tools (which are slow and limited in free version) and unfortunately I don't have an old ios device nearby for further investigation.

I created a PR.

**Comment by merobal** [comment]
Hi @nicolas-cusan did you have time to take a look at the PR?

**Comment by nicolas-cusan** [comment]
Hi @merobal I added some feedback to the PR. In any case I tested the library on iOS 13 via Browserstack and did not get any errors. Any chance you can provide more information about the iOS version?

My guess is, if there is an error in old browsers, that these versions do not support `addEventListener` on `MediaQueryList` and the old and now deprecated `addListener` needs to be used. Maybe you could try that test it and update the PR accordingly (will add this comment there too).

**Comment by nicolas-cusan** [comment]
Hi @merobal I just released a new version that catches the error. Please test it and report back. Thank you!

**Comment by merobal** [comment]
Thank you! I tested the code that crashed with `1.0.3` and works good with `1.0.4` without try-catch at our side. 🎉 

Also it didn't happen on first page-load, it happened when the user navigated to a new screen inside react scope (like after a "start screen" before a survey, then it crashed for some reason). Tested with virtual iphone x device and ios 13.0.
