### ISSUE TITLE
Better types

### ISSUE THREAD

**Issue by merobal** [nicolas-cusan/breakpoint-helper#9]
Hi,

I checked the types and noticed the return type (`Methods`) is too general.

Which results that `listenAll` being just a `Function`, 
![image](https://github.com/nicolas-cusan/breakpoint-helper/assets/5844511/d84ae105-3412-4cb0-9583-929867ee36c2)

Therefore the `listener` variable becomes `any`, also there are no arg types for the `listenAll` function.
![image](https://github.com/nicolas-cusan/breakpoint-helper/assets/5844511/ca8bd36e-ea57-4ed7-bb62-392bdbee756c)

_(I would suggest removing the `Methods` interface as the return type of the `bph` fn and letting the TypeScript compiler figure out the exact interfaces of the returned fns.)_
![image](https://github.com/nicolas-cusan/breakpoint-helper/assets/5844511/e4f3a660-f103-43cb-a95a-2b82e34f86b1)

```
function bph(config: Config): {
    getBreakpoints: () => Breakpoints;
    getMediaQuery: (name: BpNameOrNames, useMax?: boolean) => string;
    isMatching: (name: BpNameOrNames, useMax?: boolean) => boolean;
    listen: (options: ListenOptions, callback: (event: MediaQueryListEvent | MediaQueryList) => void) => ListenersReturn;
    listenAll: (callback: (bps: string[]) => void, options?: ListenAllOptions) => ListenersReturn;
}
```

**Comment by nicolas-cusan** [comment]
Hey @merobal, thanks for the input, will look into it and add your suggestions.

**Comment by merobal** [comment]
Works perfectly, thanks!
